[google_drive_service_account]
type = "service_account"
project_id = "better-pesu-acad"
private_key_id = "47356bf52a04a684c16c3c57130ea97d77e436ec"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCiATCiopyKC0gQ
+WpT6aWOPNn+1EHiS2/T2t0Xq5iDHherYjt6ivsEQLQ28fwppNFFiiMYHR8NPkAS
5XRG/P6FEwF3kmukATTk7nrVE21o2avFxofpyoKllhkAY0p70F80Rc/9e5rfx873
3ro9fS6SOlJQSYB6sRATIABlUuPORQDPNsjy8ZPRBXe+duQqFM5a3BDaTgVxYG/n
saXC3szhUKgNy0E4EuMIKU8GSxQq4/LPucjQEHW/K36l7vr7PacXhJ4rUZ+6eSYK
b/uYaoMa16I9vN8u5BW3Ks6Qn8Mfb6N5lwwb9vQsr7K7PAXIezoVGI7P8iUnoNPi
GM9bivrFAgMBAAECggEANkTzx+d1TQEOeTE0HzwLy6Qy2py8HVRr96o/mihPhMzV
3QGhLyHTiM8sD6Psdv7RY9wseW1383XA/ROEaitiD64YNbgE+wG0eGQzHaHOautQ
EYa6DOVb8qBfa7PXRba9zcL9M8ruTLygZoRkGykOKsoCvQaCVZdu7RkxSMAFtBj9
AqWMh8wWIP4hGO6qIZKfii6F5dLIA6Pf3R8HVG0mO49zMCSPgeOelpW/98MG0D2W
aMkm++rRc/8DufCXgCuv5HQPDjrjXCfWsvLxo3sAKjpfF4/xgyMMuQeWPK1/ktdL
pC2cU3GDiPySx6aAhyMjlkGHBjWOjUJh6hkho6kgmQKBgQDOL/3PmD/nqjzBXl3Q
DOGSglSr41wiZZ3SCcXDII/BVj9uT54XBUl7y1gu4vJ2s2acDfS/dUFvWa5fDwvy
bUKOgH74hWH5uSoJVtxtGj5S6K6SIUNZY+9mWOvvBZyP42Nlw+496H5tae82f61O
jooYJePB2oqlPisGektmFt61zwKBgQDJJKNmS+yhS19YSLuMB8g+wGnqRCeHOWzM
o1/Dt1DbQmyvCAncNMGD2cQ+4alHBcTznOdMajQDroC90IirTnBy9YV0XdOk5ZbQ
09WMsTFMwByv6S29E1Daay93XOK70xdKMVeMKmaOtSGBYlOAGTnLO25jyCFo4lYS
SqNpifO/KwKBgDXtfW/vfT9lWjClMto4lEMSjXzLoYxpkYafAbeQa6kAmuSKNGoG
+vpC7BSPTSVYtMy6Jbpxu6SZCy9XqyNECnVlDFCJ6l87W9BHhK2QgJ6EtywHQSs/
JR1awpKooBNOQPAb99L/XRnW7DcP289BHsNEHbbVJxAjG3O9Rr0z3BonAoGALfXo
PFS28jglxieAa0PP9r7CtNvz6Esv2CawmCkIGcG40dnVXvLTEQyucevgYTEpSr0c
gPJ3hivWkQjYYcRfn3UIlIln9fLcHkV5M1e9uxreszdl0yFZxT7erriTunVGihZy
Ob3qh0tOJ6FPESMyeITQ+Y3eTHgDUNSrOE9kWdcCgYAja+SEWsuTC+M2IQRJ1r4K
jFgJwq3y0q5qKA9/R62BFzj2YYCfFS/xvurdozdsmn86Ulzn9sZcu1xni94C8zk1
8/uxEaMpsl7h77V1yxwap5jVrGVwQnhK9zjvQzBsQkpfT1/nCB4wSbacVddqbNSl
1XYi3iKaT3+wZCdHIRmtWQ==
-----END PRIVATE KEY-----"""
client_email = "hail-mairy-service@better-pesu-acad.iam.gserviceaccount.com"
client_id = "107261674333101312935"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hail-mairy-service%40better-pesu-acad.iam.gserviceaccount.com"


[firebase_service_account]
type = "service_account"
project_id = "better-pesu-acad"
private_key_id = "47356bf52a04a684c16c3c57130ea97d77e436ec"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCiATCiopyKC0gQ
+WpT6aWOPNn+1EHiS2/T2t0Xq5iDHherYjt6ivsEQLQ28fwppNFFiiMYHR8NPkAS
5XRG/P6FEwF3kmukATTk7nrVE21o2avFxofpyoKllhkAY0p70F80Rc/9e5rfx873
3ro9fS6SOlJQSYB6sRATIABlUuPORQDPNsjy8ZPRBXe+duQqFM5a3BDaTgVxYG/n
saXC3szhUKgNy0E4EuMIKU8GSxQq4/LPucjQEHW/K36l7vr7PacXhJ4rUZ+6eSYK
b/uYaoMa16I9vN8u5BW3Ks6Qn8Mfb6N5lwwb9vQsr7K7PAXIezoVGI7P8iUnoNPi
GM9bivrFAgMBAAECggEANkTzx+d1TQEOeTE0HzwLy6Qy2py8HVRr96o/mihPhMzV
3QGhLyHTiM8sD6Psdv7RY9wseW1383XA/ROEaitiD64YNbgE+wG0eGQzHaHOautQ
EYa6DOVb8qBfa7PXRba9zcL9M8ruTLygZoRkGykOKsoCvQaCVZdu7RkxSMAFtBj9
AqWMh8wWIP4hGO6qIZKfii6F5dLIA6Pf3R8HVG0mO49zMCSPgeOelpW/98MG0D2W
aMkm++rRc/8DufCXgCuv5HQPDjrjXCfWsvLxo3sAKjpfF4/xgyMMuQeWPK1/ktdL
pC2cU3GDiPySx6aAhyMjlkGHBjWOjUJh6hkho6kgmQKBgQDOL/3PmD/nqjzBXl3Q
DOGSglSr41wiZZ3SCcXDII/BVj9uT54XBUl7y1gu4vJ2s2acDfS/dUFvWa5fDwvy
bUKOgH74hWH5uSoJVtxtGj5S6K6SIUNZY+9mWOvvBZyP42Nlw+496H5tae82f61O
jooYJePB2oqlPisGektmFt61zwKBgQDJJKNmS+yhS19YSLuMB8g+wGnqRCeHOWzM
o1/Dt1DbQmyvCAncNMGD2cQ+4alHBcTznOdMajQDroC90IirTnBy9YV0XdOk5ZbQ
09WMsTFMwByv6S29E1Daay93XOK70xdKMVeMKmaOtSGBYlOAGTnLO25jyCFo4lYS
SqNpifO/KwKBgDXtfW/vfT9lWjClMto4lEMSjXzLoYxpkYafAbeQa6kAmuSKNGoG
+vpC7BSPTSVYtMy6Jbpxu6SZCy9XqyNECnVlDFCJ6l87W9BHhK2QgJ6EtywHQSs/
JR1awpKooBNOQPAb99L/XRnW7DcP289BHsNEHbbVJxAjG3O9Rr0z3BonAoGALfXo
PFS28jglxieAa0PP9r7CtNvz6Esv2CawmCkIGcG40dnVXvLTEQyucevgYTEpSr0c
gPJ3hivWkQjYYcRfn3UIlIln9fLcHkV5M1e9uxreszdl0yFZxT7erriTunVGihZy
Ob3qh0tOJ6FPESMyeITQ+Y3eTHgDUNSrOE9kWdcCgYAja+SEWsuTC+M2IQRJ1r4K
jFgJwq3y0q5qKA9/R62BFzj2YYCfFS/xvurdozdsmn86Ulzn9sZcu1xni94C8zk1
8/uxEaMpsl7h77V1yxwap5jVrGVwQnhK9zjvQzBsQkpfT1/nCB4wSbacVddqbNSl
1XYi3iKaT3+wZCdHIRmtWQ==
-----END PRIVATE KEY-----"""
client_email = "hail-mairy-service@better-pesu-acad.iam.gserviceaccount.com"
client_id = "107261674333101312935"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hail-mairy-service%40better-pesu-acad.iam.gserviceaccount.com"
